// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBtRi2aAHg1-3tZcS4Kp3BMHhOBa5oZCI',
    appId: '1:832255754826:web:fd167001c19417e30edcb3',
    messagingSenderId: '832255754826',
    projectId: 'ronald-delacruz-porfolio-v2',
    authDomain: 'ronald-delacruz-porfolio-v2.firebaseapp.com',
    storageBucket: 'ronald-delacruz-porfolio-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkaCIKc0xH5SsMIhd1CUAyXPHAHbzVqnM',
    appId: '1:832255754826:android:b42ebe9ee104a9ea0edcb3',
    messagingSenderId: '832255754826',
    projectId: 'ronald-delacruz-porfolio-v2',
    storageBucket: 'ronald-delacruz-porfolio-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADPkrUuw8U2NZFza29cT9XPe57ghYoSMk',
    appId: '1:832255754826:ios:cfbf99fb637f56590edcb3',
    messagingSenderId: '832255754826',
    projectId: 'ronald-delacruz-porfolio-v2',
    storageBucket: 'ronald-delacruz-porfolio-v2.firebasestorage.app',
    iosBundleId: 'com.example.ronaldDelaCruzPortfolioV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADPkrUuw8U2NZFza29cT9XPe57ghYoSMk',
    appId: '1:832255754826:ios:cfbf99fb637f56590edcb3',
    messagingSenderId: '832255754826',
    projectId: 'ronald-delacruz-porfolio-v2',
    storageBucket: 'ronald-delacruz-porfolio-v2.firebasestorage.app',
    iosBundleId: 'com.example.ronaldDelaCruzPortfolioV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBtRi2aAHg1-3tZcS4Kp3BMHhOBa5oZCI',
    appId: '1:832255754826:web:dabab1a95c1bae9d0edcb3',
    messagingSenderId: '832255754826',
    projectId: 'ronald-delacruz-porfolio-v2',
    authDomain: 'ronald-delacruz-porfolio-v2.firebaseapp.com',
    storageBucket: 'ronald-delacruz-porfolio-v2.firebasestorage.app',
  );
}
